// <auto-generated />
namespace TallybookServiceV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _09_20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09_20));
        
        string IMigrationMetadata.Id
        {
            get { return "201909200727312_09_20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
