// <auto-generated />
namespace TestAll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<< HEAD:TestAll/TestAll/Migrations/201908130556212_Aug0813.Designer.cs
    public sealed partial class Aug0813 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aug0813));
        
        string IMigrationMetadata.Id
        {
            get { return "201908130556212_Aug0813"; }
=======
    public sealed partial class initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201908080902364_initial"; }
>>>>>>> cf653cf276da2e49e1ea47bd628817f450c006e6:TestAll - 複製 (2)/TestAll/Migrations/201908080902364_initial.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
